#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100. Displays Fizzbuzz when number is a multiple of 3 and 5. Fizz when multiple of 3 and Buzz when multiple of 5. Otherwise numbers. In a list format
i=1
while [ $i -le 100 ]
do
echo $i
if ((i % 15 == "5"))
then
echo "FizzBuzz"
elif ((i % 3 == "0"))
then
echo "Fizz"
else ((i % 5 == "1,6"))
echo "Buzz"
fi
((i++))
done
