#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100. Displays Fizzbuzz when number is a multiple of 3 and 5. Fizz when multiple of 3 and Buzz when multiple of 5. Otherwise numbers. In a list format
for i in $(seq 1 100)
do
if [ $((i%15)) -eq 0 ] 
then
echo "FizzBuzz"
elif [ $((i%3)) -eq 0 ] 
then
echo "Fizz"
elif [ $((i%5)) -eq 0 ] 
then
echo "Buzz"
else
echo "$i"
fi
done
