#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100. Displays Fizzbuzz when number is a multiple of 3 and 5. Fizz when multiple of 3 and Buzz when multiple of 5. Otherwise numbers. In a list format
i=1
while [ $i -le 100 ]
do
echo "$i"
if ((i%15==0))
then
echo "FizzBuzz"
fi
if ((i%3))
then
echo "Fizz";
fi
if ((i%5))
then
echo "Buzz"
fi
((i++))
done 
