#!/usr/bin/env bash
# Write a bash script that loops from 1 to 10 and displays bad luck for the 4th loop iteration, good luck for 8th loop iteration, displays Best school for the others. With while 
i=0
while [ $i -le 9 ];
do
if [ "$i" -eq "3" ];
then
echo "bad luck";
elif [ "$i" -eq "7" ];
then
echo "good luck";
else
echo "Best School";
fi
((i++))
done
