#!/usr/bin/env bash
# Bash script displays the content of current directory ina list format where only the part of the name after dash is displayed. Using for loop, not display hidden files.
for var in list;
do
ls | cut -f 2
done

