#!/usr/bin/env bash
# bash script that gives you information about the school file. Using if and else.
var=FILE
if [[ -e $FILE ]];
then
echo "school file exists";
else
echo "school does not exist";
fi

if [[ -s $FILE ]];
then 
echo "school file is empty";
else
echo "school is not empty";
fi

if [[ -f $FILE ]];
then
echo "school file is regular file";
fi

