#!/usr/bin/env bash
#bash script that gives you information about the school file. Using if and else.
if [ -e $i ]; then
echo "school file exists"
if [ -s $i ]; then
echo "school file is empty"
else
echo "school file is not empty"
fi
if [ -f $i ]; then
echo "school is a regular file"
fi
else
echo "school does not exist"
fi
