#!/usr/bin/env bash
#bash script that gives you information about the school file. Using if and else.

#!/usr/bin/env bash
if [[ -e i ]];
then
echo "school file exists";
else
echo "school does not exist";
fi

if [[ -s i ]];
then
echo "school file is empty";
else
echo "school is not empty";
fi

if [[ -f i ]];
then
echo "school file is regular file";
else
echo "nothing";
fi
