#!/bin/bash
drwxr-xr-x 2 root root 58 May 19 02:13 .
drwxr-xr-x 4 root root 49 May 19 01:40 ..
-rwxr--r-- 1 root root 16 May 19 02:13 0-current_working_directory
-rw-r--r-- 1 root root  7 May 19 01:44 README.md

