#!/usr/bin/env bash
# using previous exercise command, write a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009
ps -aux -f | tr [:alpha:] bash
