#!/usr/bin/env bash
# Programs that are detached from the terminal and running in the background are called daemons or processes, need to be managed. The general minimum set of instructions is: start, restart and stop. The most popular way of doing so on Unix system is to use the init scripts. Write a manage_my_process Bash script that: Indefinitely writes I am alive! to the file /tmp/my_process In between every I am alive! message, the program should pause for 2 seconds
while true
do 
echo "I am alive!" 
sleep 2
done
